/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SpringSandBox;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        assertEquals("app should have a greeting", 1,1);
    }
}
